version: '3.7'
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./back/ecommerce-services:/var/www/html
      - ./back/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
     - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./back/ecommerce-services:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

  front:
    build: .
    command: npm run dev
    container_name: front
    volumes:
      - .:/front/ecommerce
      - ./node_modules:/ecommerce/node_modules
    ports:
      - 5000:80
    environment:
      HOST: 0.0.0.0
    networks:
      - laravel

networks:
  laravel: